---

# Play 1

- name: Add a user, set their password, set account to never expire and add welcome file to their home directory
  hosts: awsloki
  become: true
  vars:
    dev_username: 'tfleming'  # Defining this variable will allow you to change the username and use this one playbook to create any user you wish
  tasks:

  - name: Add user '{{ dev_username }}], and set their password, and make sure account never expires
    tags: useradd,redhat,centos
    user:
      name: '{{ dev_username }}'
      state: present
      password: $6$gizvRtzRm101.Rxd$CZD2qFvrIfw2of18M/eWvRQURfc8g8xEFaGjp.3Ri2/1u3BG7te3b8KTzNMJmXAH.aflsCkIKTcbLrn0Krbys0    # To generate a hashed password: $ openssl passwd -6 'chosen_password'
      expires: -1

  - name: Copy Welcome File to '{{ dev_username}}' home directory
    tags: useradd,redhat,centos
    copy:
      src: welcome.txt
      dest: /home/{{ dev_username }}/welcome_dir/  # If you end with a /, and the directory doesn't exist, it will create the directory. If you end with a filename, the file path must already exist. 
      owner: '{{ dev_username }}'
      group: '{{ dev_username }}'
      mode: 0664
      
  - name: Make Sure file exists
    tags: verify
    stat:
      path: /home/{{ dev_username }}/welcome_dir/welcome.txt
    register: file_check

  - name: Verbose Verification
    tags: verify
    debug:
      msg:  "The 'welcome.txt' file was copied!"
    when: file_check.stat.exists == true

# Play 2 

- name: Copy aloha.jpg file using full path
  hosts: awsloki
  become: true
  vars:
    dev_username: 'tfleming'
  tasks:

  - name: Copy aloha.jpg to '{{ dev_username}}' home directory using full path
    tags: copy
    copy:
      src: /home/lalohikea/aloha.jpg
      dest: /home/{{ dev_username }}/ 
      owner: '{{ dev_username }}'
      group: '{{ dev_username }}'
      mode: 0664
