---
# Play 1: Targeting All servers
- name: The following two tasks will target all nodes
  hosts: all
  become: true
  pre_tasks: #This ensures that these tasks happen before anything else is run in the playbook. 

  - name: Install updates on Ubuntu
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install updates on RedHat
    package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

# Play 2: Targeting web-servers
- name: The following tasks will target web_servers
  hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for RedHat servers
    dnf:
      name:
       - httpd
       - php
      state: latest
    when: ansible_distribution == "RedHat"

# Play 3: Targeting db_servers
- name: The following tasks will target db_servers
  hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package (Ubuntu)
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install mariadb package (RedHat)
    package:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"

# Play 4: Targeting file_servers
- name: The following tasks will target file_servers
  hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    package:
      name: samba
      state: latest
